[project]

name = "universalSOAP"
version= "0.1.1"
requires-python = ">=3.9"

readme = "README.md"
license = { file = "LICENSE" }

scripts = { universalSOAP_descriptors = "universalSOAP.cli.write_descriptor_quantities:main" }

[tool.setuptools.packages.find]

exclude = [ "calculations*" ]
