#!/usr/bin/env python

import glob, os
import ase.data

for el in ase.data.chemical_symbols[1:]:
    Z = ase.data.atomic_numbers[el]
    if Z in [2,10,18,36,54,86]:
        continue
    if Z in [1,7,8]:
        scale = 1.8
    elif Z in [3,4,11,12] or Z > 18:
        scale = 0.75
    else:
        scale = ""
    print("./do_auto_length_scale.sh {} {} &".format(Z,scale))
